# Generated by Django 5.0 on 2024-01-01 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='slot',
            field=models.IntegerField(default=50),
            preserve_default=False,
        ),
    ]
